version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepassword
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./weather-app-backend
    image: backend:latest
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: exampleuser
      DB_PASSWORD: examplepassword
      DB_NAME: exampledb
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./weather-app-frontend
    image: frontend:latest
    container_name: weather-app-frontend
    environment:
      REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL:-http://backend:3000}
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mysql-data:
